name: CI/CD Pipeline

on:
  push:
    branches: [main] # Запускать только при пуше в ветку main

jobs:
  checks:
    uses: ./.github/workflows/pr-check.yml

  build:
    needs: checks
    runs-on: ubuntu-latest # Используем GitHub-hosted runner с Ubuntu

    steps:
      - name: Логин в Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Сборка Docker-образа
        run: docker build -t ${{ secrets.DOCKER_USER }}/my-node-app:${{ github.sha }} .

      - name: Публикация Docker-образа
        run: docker push ${{ secrets.DOCKER_USER }}/my-node-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
            docker pull ${{ secrets.DOCKER_USER }}/my-node-app:${{ github.sha }}
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker run -d --name my-node-app -p 4545:4545 ${{ secrets.DOCKER_USER }}/my-node-app:${{ github.sha }}
